### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/x.ip5/Makefile.srf06

CONTIKI_TARGET_DIRS += x.ip5/cc13xx
