DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

all: x.ip5-demo

PROJECT_SOURCEFILES += cetic-6lbr-client.c broadcast-example.c
PROJECT_SOURCEFILES += httpd-simple.c 

CONTIKI_WITH_IPV6 = 1

CONTIKI=../../..
include $(CONTIKI)/Makefile.include
